// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtNNcUMAxFKDhX6s9K7YpmwkaxCx234U0',
    appId: '1:101074684453:web:54c82dda7fc4777fdc4dcc',
    messagingSenderId: '101074684453',
    projectId: 'tunitrain-4c9e1',
    authDomain: 'tunitrain-4c9e1.firebaseapp.com',
    storageBucket: 'tunitrain-4c9e1.firebasestorage.app',
    measurementId: 'G-F79E42GLJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-8lKrcKYx4BFF5Vn8I0C778m2cdwCkU',
    appId: '1:101074684453:android:19420ca85698a1bfdc4dcc',
    messagingSenderId: '101074684453',
    projectId: 'tunitrain-4c9e1',
    storageBucket: 'tunitrain-4c9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvPb4o2tO1v5B0MZcbjtcq1vedMH1nL4',
    appId: '1:101074684453:ios:621f68b6292f6e24dc4dcc',
    messagingSenderId: '101074684453',
    projectId: 'tunitrain-4c9e1',
    storageBucket: 'tunitrain-4c9e1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrvPb4o2tO1v5B0MZcbjtcq1vedMH1nL4',
    appId: '1:101074684453:ios:621f68b6292f6e24dc4dcc',
    messagingSenderId: '101074684453',
    projectId: 'tunitrain-4c9e1',
    storageBucket: 'tunitrain-4c9e1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtNNcUMAxFKDhX6s9K7YpmwkaxCx234U0',
    appId: '1:101074684453:web:85a4490f05978093dc4dcc',
    messagingSenderId: '101074684453',
    projectId: 'tunitrain-4c9e1',
    authDomain: 'tunitrain-4c9e1.firebaseapp.com',
    storageBucket: 'tunitrain-4c9e1.firebasestorage.app',
    measurementId: 'G-NHRC993ZJ2',
  );
}
